export enum MEAL_CONTENT_STRINGS {
  dashboardTitle = 'dashboard_title',
  headerTitle = 'header_title',
  buttonDonateAMeal = 'button_donate-a-meal',
  buttonDonate = 'button_donate',
  donationPolicyTitle = 'label_donation-policy-title',
  donationPolicyContent = 'label_donation-policy-content',
  donationInstructions = 'label_donation-instructions',
  completeMessage = 'label_donation-complete-message',
  fundingAccounts = 'label_funding-accounts',
  labelMealsToDonate = 'label_meals-to-donate',
  amountToDonate = 'label_amount-to-donate',
  labelMeal = 'label_meal',
  dialogLabelSuccess = 'dialog_label_success',
  donationConfirmationTitle = 'dialog_title_donation-confirmation',
  donateAmount = 'label_donate-amount',
  labelAccount = 'label_account',
  buttonDone = 'button_done',
  buttonCancel = 'button_cancel',
  formErrorMealsPositiveWhole = 'form-error_meals_positive-whole',
  formErrorInvalideFormat = 'form-error_invalid-format',
  formErrorEmpty = 'form-error_empty',
  formErrorInsufficientFunds = 'form-error_insufficient-funds',
  formErrorSelectedAccount = 'form-error_select-account',
}
