image: maven:3.3.9

definitions:
  services:
    docker:
      memory: 3072
  steps:
    - step: &build-and-test
        name: Build and test
        image: atlassian/default-image:3
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm run test:ci
          - npm run build-appflow
    - step: &build-step
        name: SonarQube analysis
        image: node:18.1.0
        script:
          - pipe: sonarsource/sonarqube-scan:2.0.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL} # Get the value from the repository/workspace variable.
              SONAR_TOKEN: ${SONAR_TOKEN} # Get the value from the repository/workspace variable. You shouldn't set secret in clear text here.
  caches:
    sonar: ~/.sonar

clone:
  depth: full

pipelines:
  branches:
    release-*: # or the name of your main branch
      - step: *build-and-test
  pull-requests:
    '**':
      - step:
          name: Build and test
          image: node:18-alpine
          script:
            - npm install
            - npm run lint
            - npm run test:ci
            - npm run build-appflow
  custom:
    release-update:
      - step:
          name: Release Update
          image: atlassian/default-image:3
          script:
            - apt-get update && apt-get install -y sed
            - apt-get update && apt-get install -y libplist-utils
            - cd scripts
            - chmod +x UpdateRelease.sh
            - ./UpdateRelease.sh $WEBHOOK_URL
    update-from-develop:
      - step:
          name: Update from develop
          image: atlassian/default-image:3
          script:
            - cd scripts
            - chmod +x UpdateFromDevelop.sh
            - ./UpdateFromDevelop.sh
    release-sync:
      - step:
          name: "Sync Release Branch to GitHub"
          script:
            - echo "Starting sync of Bitbucket release branch to GitHub..."
            - git remote add github $GITHUB_URL
            - touch smart.txt
            - git add smart.txt
            - git commit -m"Smart text ${BITBUCKET_BRANCH}"
            - git fetch github $GITHUB_BRANCH
            - git rebase github/$GITHUB_BRANCH
            - git push -u --force github $BITBUCKET_BRANCH:$GITHUB_BRANCH