image: maven:3.3.9

definitions:
  services:
    docker:
      memory: 3072
  steps:
    - step: &build-step
        name: SonarQube analysis
        image: node:18.1.0
        script:
          - pipe: sonarsource/sonarqube-scan:1.0.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL} # Get the value from the repository/workspace variable.
              SONAR_TOKEN: ${SONAR_TOKEN} # Get the value from the repository/workspace variable. You shouldn't set secret in clear text here.
  caches:
    sonar: ~/.sonar

clone:
  depth: full

pipelines:
  branches:
    release-*: # or the name of your main branch
      - step: *build-step
  pull-requests:
    '**':
      - step:
          name: Build and test
          image: node:18-alpine
          script:
            - npm install
            - npm run lint
            - npm run build-appflow
  custom:
    release-update:
      - step:
          name: Release Update
          image: atlassian/default-image:3
          script:
            - apt-get update && apt-get install -y sed
            - apt-get update && apt-get install -y libplist-utils
            - cd scripts
            - chmod +x UpdateRelease.sh
            - ./UpdateRelease.sh $WEBHOOK_URL