pipelines:
  pull-requests:
    feature/*: # this will run on any branch with a feature/ prefix that has a PR open
      - step:
          script:
            - npm i
            - npm run build-prod
    bugfix/*: # this will run on any branch with a bugfix/ prefix that has a PR open
      - step:
          script:
            - npm i
            - npm run build-prod
