version: 0.2

env:
  variables:
    RPM_VERSION: "2.43.2"
phases:
  install:
    commands:
      - echo **** Installing required packages ****
      - yum install epel-release -y
      - yum install nodejs -y
      - yum install npm -y
      - yum install rpm-build -y
      - npm install -g cordova ionic
  pre_build:
    commands:
      - echo **** Running pre-build, creating rpm directories ****
      - mkdir BUILD RPMS SOURCES SPECS SRPMS
      - mv ./student.spec SPECS

      - echo **** Performing Ionic build ****

      - npm install
      - ionic build --prod

      - mkdir student
      - cp -r ./www/* ./student
      - cp terms.html ./student
      - cp robots.txt ./student 
      - echo **** Perform tar ****
      - tar -zcvf ./SOURCES/student.tar.gz student
  build:
    commands:
      - echo **** Triggering RPM build ****
      - rpmbuild --define "_topdir `pwd`" --define "_version $RPM_VERSION" --define '_release 1' -bb SPECS/student.spec
  post_build:
    commands:
      - echo **** Entered the post_build phase... ****
      - echo **** Build completed on `date` ****
artifacts:
  files:
      - RPMS/noarch/student*.rpm
      # - SPECS/appspec.yml
  discard-paths: yes