version: 0.2

env:
  variables:
    RPM_VERSION: "2.54"
  parameter-store: 
    BUILD_NUMBER: "build-config-cbord-student-build-number"

phases:
  install:
    commands:
      - echo **** Installing required packages ****
      - yum install epel-release -y
      - curl -sL https://rpm.nodesource.com/setup_10.x | bash -
      - yum install nodejs -y
      - node --version
      - npm --version
      - yum install rpm-build -y
      - npm install -g ionic
      - npm install -g cordova
  pre_build:
    commands:
      - echo **** Running pre-build, creating rpm directories ****
      - mkdir BUILD RPMS SOURCES SPECS SRPMS
      - mv ./student.spec SPECS

      - echo **** Set Android SDK Environment Variables ****
      - export ANDROID_HOME=$(pwd)/android-sdk
      - export ANDROID_SDK_ROOT=$(pwd)/android-sdk
      - export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
      - export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
      - export PATH=$PATH:$ANDROID_SDK_ROOT/emulator

      - echo **** Performing Ionic build ****
      - npm install -g jdk
      - npm install
      - ionic build --prod
      - ionic cordova build android

      - mkdir student
      - cp -r ./www/* ./student
      - cp terms.html ./student
      - cp robots.txt ./student 
      - echo **** Perform tar ****
      - tar -zcvf ./SOURCES/student.tar.gz student
  build:
    commands:
      - echo "**** Running shell script ****"
      - echo "Sending RPM_VERSION=$RPM_VERSION"
      - sh buildcommands.sh $RPM_VERSION $BUILD_NUMBER
      - echo "Finished shell script"
  post_build:
    commands:
      - echo **** Entered the post_build phase... ****
      - echo **** Build completed on `date` ****
artifacts:
  files:
      - RPMS/noarch/student*.rpm
      # - SPECS/appspec.yml
  discard-paths: yes