version: 0.2

phases:
  install:
    commands:
      - echo **** Installing required packages ****
      - yum install epel-release -y
      - yum install nodejs -y
      - yum install npm -y
      - yum install rpm-build -y
      - npm install -g cordova ionic
  pre_build:
    commands:
      - echo **** Running pre-build, creating rpm directories ****
      - mkdir BUILD RPMS SOURCES SPECS SRPMS
      - mv ./cbord-student.spec SPECS

      - echo **** Performing Ionic build ****

      - npm install
      - ionic build --prod

      - mkdir -p cbord-student
      - cp -r ./www/* ./cbord-student
      - cp terms.html ./cbord-student
      - cp robots.txt ./cbord-student 

      - echo **** Perform tar ****
      - tar -zcvf ./SOURCES/cbord-student.tar.gz cbord-student
  build:
    commands:
      - echo **** Triggering RPM build ****
      - rpmbuild --define "_topdir `pwd`" --define '_version 0.0.1' --define '_release 1' -bb ./SPECS/cbord-student.spec
  post_build:
    commands:
      - echo **** Entered the post_build phase... ****
      - echo **** Build completed on `date` ****
artifacts:
  files:
      - RPMS/noarch/cbord-student*.rpm
      # - SPECS/appspec.yml
  discard-paths: yes