import { generateQuestions } from '../questions/questions.mock';

import { Application, PatronApplication } from './applications.model';

export function generateApplication(): Application {
  return {} as Application;
}

export function generatePatronApplication(_: any, index: number): PatronApplication {
  return {
    applicationDefinitionId: 100 + index,
    createdDateTime: '0001-01-01T00:00:00',
    submittedDateTime: null,
    acceptedDateTime: null,
    cancelledDateTime: null,
    modifiedDate: null,
    patronId: 8001138,
    isApplicationSubmitted: false,
    isApplicationAccepted: false,
    isApplicationCanceled: false,
    applicationTitle: `New application ${index + 1}`,
    applicationTerm: 46,
    applicationFormJson: JSON.stringify(generateQuestions()),
  };
}

export function generatePatronApplications(amount: number = 3): PatronApplication[] {
  return Array.apply(null, Array(amount)).map(generatePatronApplication);
}

export function generateApplications(): Application[] {
  return [
    {
      id: 85,
      applicationFormJson:
        '[{"type":"header","subtype":"h1","label":"Heading 1","attribute":null},{"type":"paragraph","subtype":"p","label":"Fill out the form to the bestest of your abilitestest.&nbsp;","attribute":null},{"type":"header","subtype":"h2","label":"Personal Info","attribute":null},{"type":"text","label":"Name","name":"text-1568748841830","subtype":"text","attribute":"Name"},{"type":"text","label":"ID Number","name":"text-1568748852914","subtype":"text","attribute":"ID Number"},{"type":"text","label":"Email","name":"text-1568748852251","subtype":"text","attribute":"Email"},{"type":"date","label":"Date of birth","name":"date-1568748899067","attribute":"Date of birth"},{"type":"header","subtype":"h2","label":"Optional Info","attribute":null},{"type":"paragraph","subtype":"p","label":"This information is completely optional.","attribute":null},{"type":"checkbox-group","label":"Gender","name":"checkbox-group-1568748935545","values":[{"label":"Option 1","value":"option-1","selected":true}],"attribute":"Gender"},{"type":"text","label":"Phone Number","name":"text-1568748932732","subtype":"text","attribute":"Phone Number"}]',
      applicationAvailableStartDateTime: '2020-01-01T00:00:00',
      applicationAvailableEndDateTime: '2020-07-31T00:00:00',
      cancellationDateTime: '0001-01-01T00:00:00',
      expirationDateTime: '0001-01-01T00:00:00',
      applicationTypeId: 20,
      termId: 10,
      numberOfDaysToExpire: 0,
      applicationDescription: null,
      applicationTitle: 'AGHForm',
      applicationAttributes: [
        {
          applicationAttributeId: 59,
          applicationDefinitionId: 85,
          consumerAttributeId: 2741,
          applicationAttributeValue: 'Graduate',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
      ],
    },
    {
      id: 83,
      applicationFormJson:
        '[{"type":"text","label":"Email","name":"text-1568322512899","subtype":"text","attribute":"Email"},{"type":"checkbox-group","label":"Gender","name":"checkbox-group-1568322515837","values":[{"label":"Option 1","value":"option-1","selected":true}],"attribute":"Gender"},{"type":"text","label":"ID Number","name":"text-1568322517307","subtype":"text","attribute":"ID Number"},{"type":"text","label":"Name","name":"text-1568322518587","subtype":"text","attribute":"Name"}]',
      applicationAvailableStartDateTime: '2019-09-01T00:00:00',
      applicationAvailableEndDateTime: '2019-09-26T00:00:00',
      cancellationDateTime: '0001-01-01T00:00:00',
      expirationDateTime: '0001-01-01T00:00:00',
      applicationTypeId: 17,
      termId: 9,
      numberOfDaysToExpire: 0,
      applicationDescription: null,
      applicationTitle: 'MXD appl select patr mult attribs',
      applicationAttributes: [
        {
          applicationAttributeId: 58,
          applicationDefinitionId: 83,
          consumerAttributeId: 2310,
          applicationAttributeValue: 'Sophomore',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
        {
          applicationAttributeId: 57,
          applicationDefinitionId: 83,
          consumerAttributeId: 2310,
          applicationAttributeValue: 'Freshman',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
      ],
    },
    {
      id: 80,
      applicationFormJson:
        '[{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"checkbox-group","label":"Starting Semester","name":"checkbox-group-1568322477524","values":[{"label":"Option 1","value":"option-1","selected":true}],"attribute":"Starting Semester"},{"type":"date","label":"Date of birth","name":"date-1568322478211","attribute":"Date of birth"},{"type":"text","label":"Email","name":"text-1568322478627","subtype":"text","attribute":"Email"},{"type":"checkbox-group","label":"Gender","name":"checkbox-group-1568322479183","values":[{"label":"Option 1","value":"option-1","selected":true}],"attribute":"Gender"},{"type":"text","label":"ID Number","name":"text-1568322479837","subtype":"text","attribute":"ID Number"},{"type":"text","label":"Name","name":"text-1568322480243","subtype":"text","attribute":"Name"},{"type":"paragraph","subtype":"p","label":"Paragraph","attribute":null},{"type":"paragraph","subtype":"p","label":"Paragraph","attribute":null}]',
      applicationAvailableStartDateTime: '2019-10-10T00:00:00',
      applicationAvailableEndDateTime: '2019-09-19T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 21,
      termId: 11,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'kim3',
      applicationAttributes: [],
    },
    {
      id: 79,
      applicationFormJson:
        '[{"type":"header","subtype":"h1","label":"Welcome Students","attribute":null},{"type":"date","label":"Date of birth","name":"date-1568319857403","attribute":"Date of birth"},{"type":"text","label":"Email","name":"text-1568319860156","subtype":"text","attribute":"Email"},{"type":"checkbox-group","label":"Gender","name":"checkbox-group-1568319861339","values":[{"label":"Option 1","value":"option-1","selected":true}],"attribute":"Gender"},{"type":"text","label":"ID Number","name":"text-1568319862491","subtype":"text","attribute":"ID Number"},{"type":"paragraph","subtype":"p","label":"Welcome to the new school year!!! i hope that you are ready to rock and roll!!!","attribute":null},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null}]',
      applicationAvailableStartDateTime: '2019-09-12T00:00:00',
      applicationAvailableEndDateTime: '2020-09-12T00:00:00',
      cancellationDateTime: '0001-01-01T00:00:00',
      expirationDateTime: '0001-01-01T00:00:00',
      applicationTypeId: 18,
      termId: 6,
      numberOfDaysToExpire: 0,
      applicationDescription: null,
      applicationTitle: 'kim2',
      applicationAttributes: [
        {
          applicationAttributeId: 46,
          applicationDefinitionId: 79,
          consumerAttributeId: 2310,
          applicationAttributeValue: 'Junior',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
      ],
    },
    {
      id: 78,
      applicationFormJson: '{}',
      applicationAvailableStartDateTime: '2019-09-14T00:00:00',
      applicationAvailableEndDateTime: '2019-09-14T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 17,
      termId: 5,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'kim',
      applicationAttributes: [],
    },
    {
      id: 70,
      applicationFormJson:
        '[{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"select","label":"Email","name":"select-1568312465119","values":[{"label":"Option 1","value":"option-1","selected":true},{"label":"Option 2","value":"option-2"},{"label":"Option 3","value":"option-3"}],"attribute":"Email"},{"type":"date","label":"Date of birth","name":"date-1568312465877","attribute":"Date of birth"},{"type":"text","label":"ID Number","name":"text-1568312466519","subtype":"text","attribute":"ID Number"},{"type":"paragraph","subtype":"p","label":"Paragraph","attribute":null}]',
      applicationAvailableStartDateTime: '2019-09-26T00:00:00',
      applicationAvailableEndDateTime: '2019-11-14T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 20,
      termId: 57,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'form success :)',
      applicationAttributes: [],
    },
    {
      id: 68,
      applicationFormJson:
        '[{"type":"header","subtype":"h1","label":"CBORD University New Student Application","attribute":null},{"type":"paragraph","subtype":"p","label":"We are so excited you have chosen to live on campus at CBORD University!&nbsp; Please fill out the following application and submit it to reserve a space on campus.&nbsp; If you have any questions, please notify us at 555-555-5555.","attribute":null},{"type":"text","label":"Preferred Name","name":"text-1568315394169","subtype":"text","attribute":"Name"},{"type":"text","label":"University Student ID Number","name":"text-1568315396303","subtype":"text","attribute":"ID Number"},{"type":"date","label":"Date of birth","name":"date-1568315399895","attribute":"Date of birth"},{"type":"textarea","label":"Cell Phone Number","name":"textarea-1568315408199","subtype":"textarea","attribute":"Phone Number"},{"type":"text","label":"Secondary Email Address","name":"text-1568315409856","subtype":"text","attribute":"Email"},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"checkbox-group","required":true,"label":"Gender","name":"checkbox-group-1568315413042","values":[{"label":"Female","value":"Female","selected":true},{"label":"Male","value":"Male","selected":true},{"label":"Transgender Female","value":"Transgender Female","selected":true},{"label":"Transgender Male","value":"Transgender Male","selected":true},{"label":"Non-binary","value":"Non-binary","selected":true}],"attribute":"Gender"},{"type":"checkbox-group","label":"Move In Semester","name":"checkbox-group-1568315414321","values":[{"label":"Fall 2020","value":"Fall 2020","selected":true},{"label":"Spring 2021","value":"Spring 2021","selected":true}],"attribute":"Starting Semester"},{"type":"text","label":"Graduation Year","name":"text-1568315415312","subtype":"text","attribute":"Year"},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"checkbox-group","required":true,"label":"Gender","name":"checkbox-group-1568315413042","values":[{"label":"Female","value":"Female","selected":true},{"label":"Male","value":"Male","selected":true},{"label":"Transgender Female","value":"Transgender Female","selected":true},{"label":"Transgender Male","value":"Transgender Male","selected":true},{"label":"Non-binary","value":"Non-binary","selected":true}],"attribute":"Gender"},{"type":"checkbox-group","label":"Move In Semester","name":"checkbox-group-1568315414321","values":[{"label":"Fall 2020","value":"Fall 2020","selected":true},{"label":"Spring 2021","value":"Spring 2021","selected":true}],"attribute":"Starting Semester"},{"type":"text","label":"Graduation Year","name":"text-1568315415312","subtype":"text","attribute":"Year"},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"checkbox-group","required":true,"label":"Gender","name":"checkbox-group-1568315413042","values":[{"label":"Female","value":"Female","selected":true},{"label":"Male","value":"Male","selected":true},{"label":"Transgender Female","value":"Transgender Female","selected":true},{"label":"Transgender Male","value":"Transgender Male","selected":true},{"label":"Non-binary","value":"Non-binary","selected":true}],"attribute":"Gender"},{"type":"checkbox-group","label":"Move In Semester","name":"checkbox-group-1568315414321","values":[{"label":"Fall 2020","value":"Fall 2020","selected":true},{"label":"Spring 2021","value":"Spring 2021","selected":true}],"attribute":"Starting Semester"},{"type":"text","label":"Graduation Year","name":"text-1568315415312","subtype":"text","attribute":"Year"},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"checkbox-group","required":true,"label":"Gender","name":"checkbox-group-1568315413042","values":[{"label":"Female","value":"Female","selected":true},{"label":"Male","value":"Male","selected":true},{"label":"Transgender Female","value":"Transgender Female","selected":true},{"label":"Transgender Male","value":"Transgender Male","selected":true},{"label":"Non-binary","value":"Non-binary","selected":true}],"attribute":"Gender"},{"type":"checkbox-group","label":"Move In Semester","name":"checkbox-group-1568315414321","values":[{"label":"Fall 2020","value":"Fall 2020","selected":true},{"label":"Spring 2021","value":"Spring 2021","selected":true}],"attribute":"Starting Semester"},{"type":"text","label":"Graduation Year","name":"text-1568315415312","subtype":"text","attribute":"Year"},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"checkbox-group","required":true,"label":"Gender","name":"checkbox-group-1568315413042","values":[{"label":"Female","value":"Female","selected":true},{"label":"Male","value":"Male","selected":true},{"label":"Transgender Female","value":"Transgender Female","selected":true},{"label":"Transgender Male","value":"Transgender Male","selected":true},{"label":"Non-binary","value":"Non-binary","selected":true}],"attribute":"Gender"},{"type":"checkbox-group","label":"Move In Semester","name":"checkbox-group-1568315414321","values":[{"label":"Fall 2020","value":"Fall 2020","selected":true},{"label":"Spring 2021","value":"Spring 2021","selected":true}],"attribute":"Starting Semester"},{"type":"text","label":"Graduation Year","name":"text-1568315415312","subtype":"text","attribute":"Year"},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"checkbox-group","required":true,"label":"Gender","name":"checkbox-group-1568315413042","values":[{"label":"Female","value":"Female","selected":true},{"label":"Male","value":"Male","selected":true},{"label":"Transgender Female","value":"Transgender Female","selected":true},{"label":"Transgender Male","value":"Transgender Male","selected":true},{"label":"Non-binary","value":"Non-binary","selected":true}],"attribute":"Gender"},{"type":"checkbox-group","label":"Move In Semester","name":"checkbox-group-1568315414321","values":[{"label":"Fall 2020","value":"Fall 2020","selected":true},{"label":"Spring 2021","value":"Spring 2021","selected":true}],"attribute":"Starting Semester"},{"type":"text","label":"Graduation Year","name":"text-1568315415312","subtype":"text","attribute":"Year"}]',
      applicationAvailableStartDateTime: '2019-09-02T00:00:00',
      applicationAvailableEndDateTime: '2019-09-30T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 2,
      termId: 60,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'SLH New Student Application',
      applicationAttributes: [
        {
          applicationAttributeId: 39,
          applicationDefinitionId: 68,
          consumerAttributeId: 2310,
          applicationAttributeValue: 'Junior',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
        {
          applicationAttributeId: 40,
          applicationDefinitionId: 68,
          consumerAttributeId: 2310,
          applicationAttributeValue: 'Senior',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
      ],
    },
    {
      id: 67,
      applicationFormJson:
        '[{"type":"paragraph","subtype":"p","label":"Paragraph","attribute":null},{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"select","label":"Email","name":"select-1568136167524","values":[{"label":"Option 1","value":"option-1","selected":true},{"label":"Option 2","value":"option-2"},{"label":"Option 3","value":"option-3"}],"attribute":"Email"},{"type":"date","label":"Date of birth","name":"date-1568136168503","attribute":"Date of birth"},{"type":"text","label":"ID Number","name":"text-1568136169061","subtype":"text","attribute":"ID Number"},{"type":"text","label":"Phone Number","name":"text-1568136188983","subtype":"text","attribute":"Phone Number"},{"type":"checkbox-group","label":"Starting Semester","name":"checkbox-group-1568136188120","values":[{"label":"Option 1","value":"option-1","selected":true}],"attribute":"Starting Semester"},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"paragraph","subtype":"p","label":"Paragraph","attribute":null},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"paragraph","subtype":"p","label":"Paragraph","attribute":null},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"paragraph","subtype":"p","label":"Paragraph","attribute":null},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"paragraph","subtype":"p","label":"Paragraph","attribute":null},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"paragraph","subtype":"p","label":"Paragraph","attribute":null}]',
      applicationAvailableStartDateTime: '2019-09-19T00:00:00',
      applicationAvailableEndDateTime: '2019-09-28T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 18,
      termId: 59,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'formopedia',
      applicationAttributes: [],
    },
    {
      id: 65,
      applicationFormJson: '{}',
      applicationAvailableStartDateTime: '2019-09-02T00:00:00',
      applicationAvailableEndDateTime: '2020-02-20T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 14,
      termId: 59,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'last test form',
      applicationAttributes: [],
    },
    {
      id: 64,
      applicationFormJson:
        '[{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"text","label":"Name","name":"text-1568129841765","subtype":"text","attribute":"Name"},{"type":"date","label":"Date of birth","name":"date-1568129816131","attribute":"Date of birth"},{"type":"checkbox-group","label":"Gender","name":"checkbox-group-1568129819219","values":[{"label":"Option 1","value":"option-1","selected":true}],"attribute":"Gender"},{"type":"text","label":"Email","name":"text-1568129838419","subtype":"text","attribute":"Email"}]',
      applicationAvailableStartDateTime: '2019-09-18T00:00:00',
      applicationAvailableEndDateTime: '2019-09-30T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 24,
      termId: 60,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'another application',
      applicationAttributes: [
        {
          applicationAttributeId: 24,
          applicationDefinitionId: 64,
          consumerAttributeId: 2742,
          applicationAttributeValue: 'Anthropology',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
        {
          applicationAttributeId: 25,
          applicationDefinitionId: 64,
          consumerAttributeId: 2742,
          applicationAttributeValue: 'Applied & Computational Mathematics',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
        {
          applicationAttributeId: 26,
          applicationDefinitionId: 64,
          consumerAttributeId: 2742,
          applicationAttributeValue: 'Architecture',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
      ],
    },
    {
      id: 62,
      applicationFormJson: '[]',
      applicationAvailableStartDateTime: '2019-09-26T00:00:00',
      applicationAvailableEndDateTime: '2019-09-30T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 20,
      termId: 60,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'silly form',
      applicationAttributes: [],
    },
    {
      id: 61,
      applicationFormJson:
        '[{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"date","label":"Date of birth","name":"date-1568318335723","attribute":"Date of birth"},{"type":"text","label":"Email","name":"text-1568318338348","subtype":"text","attribute":"Email"},{"type":"text","label":"ID Number","name":"text-1568318339563","subtype":"text","attribute":"ID Number"},{"type":"text","label":"Name","name":"text-1568318340677","subtype":"text","attribute":"Name"}]',
      applicationAvailableStartDateTime: '2019-09-06T00:00:00',
      applicationAvailableEndDateTime: '2019-12-09T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 2,
      termId: 5,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'MXD appl2',
      applicationAttributes: [
        {
          applicationAttributeId: 52,
          applicationDefinitionId: 61,
          consumerAttributeId: 2397,
          applicationAttributeValue: 'Graduate',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
      ],
    },
    {
      id: 60,
      applicationFormJson:
        '[{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"text","label":"Email","name":"text-1567796567040","subtype":"text","attribute":"Email"},{"type":"text","label":"Name","name":"text-1567796575175","subtype":"text","attribute":"Name"},{"type":"select","label":"Year","name":"select-1567796584910","values":[{"label":"Option 1","value":"option-1","selected":true},{"label":"Option 2","value":"option-2"},{"label":"Option 3","value":"option-3"}],"attribute":"Year"}]',
      applicationAvailableStartDateTime: '2019-09-06T00:00:00',
      applicationAvailableEndDateTime: '2019-12-07T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 13,
      termId: 3,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'MXD appl1',
      applicationAttributes: [
        {
          applicationAttributeId: 19,
          applicationDefinitionId: 60,
          consumerAttributeId: 2741,
          applicationAttributeValue: 'Undergraduate',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
      ],
    },
    {
      id: 55,
      applicationFormJson:
        '[{"type":"header","subtype":"h1","label":"Header","attribute":null},{"type":"paragraph","subtype":"p","label":"Paragraph","attribute":null},{"type":"text","label":"Email","name":"text-1567795970231","subtype":"text","attribute":"Email"},{"type":"date","label":"Date of birth","name":"date-1567795971196","attribute":"Date of birth"},{"type":"text","label":"ID Number","name":"text-1567795971638","subtype":"text","attribute":"ID Number"}]',
      applicationAvailableStartDateTime: '2019-08-12T00:00:00',
      applicationAvailableEndDateTime: '2019-10-24T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 6,
      termId: 51,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'Test Failure',
      applicationAttributes: [
        {
          applicationAttributeId: 17,
          applicationDefinitionId: 55,
          consumerAttributeId: 2310,
          applicationAttributeValue: 'Freshman',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
        {
          applicationAttributeId: 18,
          applicationDefinitionId: 55,
          consumerAttributeId: 2310,
          applicationAttributeValue: 'Junior',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
      ],
    },
    {
      id: 54,
      applicationFormJson:
        '[{"type":"text","label":"Email","name":"text-1566585778516","subtype":"text","attribute":"Email"},{"type":"date","label":"Date of birth","name":"date-1566585779491","attribute":"Date of birth"},{"type":"text","label":"ID Number","name":"text-1566585780661","subtype":"text","attribute":"ID Number"},{"type":"checkbox-group","label":"Starting Semester","name":"checkbox-group-1566586578392","values":[{"label":"Option 1","value":"option-1","selected":true}],"attribute":"Starting Semester"}]',
      applicationAvailableStartDateTime: '2019-08-28T00:00:00',
      applicationAvailableEndDateTime: '2019-10-25T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 9,
      termId: 62,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'testing 22',
      applicationAttributes: [
        {
          applicationAttributeId: 13,
          applicationDefinitionId: 54,
          consumerAttributeId: 2310,
          applicationAttributeValue: 'Freshman',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
      ],
    },
    {
      id: 53,
      applicationFormJson:
        '[{"type":"select","label":"Email","name":"select-1566585916525","values":[{"label":"Option 1","value":"option-1","selected":true},{"label":"Option 2","value":"option-2"},{"label":"Option 3","value":"option-3"}],"attribute":"Email"},{"type":"text","label":"ID Number","name":"text-1566585917262","subtype":"text","attribute":"ID Number"},{"type":"date","label":"Date of birth","name":"date-1566585918007","attribute":"Date of birth"}]',
      applicationAvailableStartDateTime: '2019-08-09T00:00:00',
      applicationAvailableEndDateTime: '2019-12-31T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 8,
      termId: 62,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'New Form',
      applicationAttributes: [],
    },
    {
      id: 52,
      applicationFormJson:
        '[{"type":"header","subtype":"h1","label":"Summer Form 2019","attribute":null},{"type":"paragraph","subtype":"p","label":"This is a summer Form","attribute":null},{"type":"checkbox-group","label":"Gender","name":"checkbox-group-1568136288338","values":[{"label":"Option 1","value":"option-1","selected":true}],"attribute":"Gender"},{"type":"text","label":"Email","name":"text-1568136296989","subtype":"text","attribute":"Email"},{"type":"paragraph","subtype":"blockquote","label":"New Page","attribute":null},{"type":"paragraph","subtype":"p","label":"information about page 2","attribute":null}]',
      applicationAvailableStartDateTime: '2019-08-22T00:00:00',
      applicationAvailableEndDateTime: '2019-10-17T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 7,
      termId: 62,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'A Summer Form :)',
      applicationAttributes: [
        {
          applicationAttributeId: 36,
          applicationDefinitionId: 52,
          consumerAttributeId: 2742,
          applicationAttributeValue: 'Anthropology',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
        {
          applicationAttributeId: 37,
          applicationDefinitionId: 52,
          consumerAttributeId: 2742,
          applicationAttributeValue: 'Astrophysical Science',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
        {
          applicationAttributeId: 38,
          applicationDefinitionId: 52,
          consumerAttributeId: 2742,
          applicationAttributeValue: 'Architecture',
          isUpdated: false,
          isDeleted: false,
          isNew: false,
        },
      ],
    },
    {
      id: 51,
      applicationFormJson: '[]',
      applicationAvailableStartDateTime: '2019-08-11T00:00:00',
      applicationAvailableEndDateTime: '2020-03-11T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 6,
      termId: 62,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'another one from UI',
      applicationAttributes: [],
    },
    {
      id: 50,
      applicationFormJson: 'null',
      applicationAvailableStartDateTime: '2019-08-22T00:00:00',
      applicationAvailableEndDateTime: '2019-11-29T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 5,
      termId: 62,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'Test UI 2',
      applicationAttributes: [],
    },
    {
      id: 49,
      applicationFormJson:
        '"\\"\\\\\\"\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"null\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\"\\\\\\"\\""',
      applicationAvailableStartDateTime: '2019-08-28T00:00:00',
      applicationAvailableEndDateTime: '2019-09-28T00:00:00',
      cancellationDateTime: '2020-08-31T00:00:00',
      expirationDateTime: '2020-08-31T00:00:00',
      applicationTypeId: 4,
      termId: 62,
      numberOfDaysToExpire: 0,
      applicationDescription: 'test',
      applicationTitle: 'grep 2019 v4.0',
      applicationAttributes: [],
    },
    {
      id: 47,
      applicationFormJson: '[{"type":"header","subtype":"h1","label":"Header"}]',
      applicationAvailableStartDateTime: '2019-08-30T00:00:00',
      applicationAvailableEndDateTime: '2019-08-20T00:00:00',
      cancellationDateTime: '2019-08-31T00:00:00',
      expirationDateTime: '2019-08-31T00:00:00',
      applicationTypeId: 3,
      termId: 62,
      numberOfDaysToExpire: 0,
      applicationDescription: 'Test Application 1',
      applicationTitle: 'Summer Application 2018 test',
      applicationAttributes: [],
    },
    {
      id: 46,
      applicationFormJson:
        '"{\\"ErrorMessage\\": \\"\\",\\"ErrorDetails\\": {\\"ErrorID\\": 111,\\"Description\\":{\\"Short\\": 0,\\"Verbose\\": 20},\\"ErrorDate\\": \\"\\"}}"',
      applicationAvailableStartDateTime: '2019-08-19T00:00:00',
      applicationAvailableEndDateTime: '2019-08-19T00:00:00',
      cancellationDateTime: '2019-08-19T20:52:42.366',
      expirationDateTime: '2019-08-19T00:00:00',
      applicationTypeId: 2,
      termId: 62,
      numberOfDaysToExpire: 0,
      applicationDescription: 'Test Application 1',
      applicationTitle: 'Summer Application 2018 Dummy',
      applicationAttributes: [],
    },
  ];
}
