export enum OrderStatus {
  PENDING = 1,
  MERCHANT_SUBMITTED = 2,
  MERCHANT_ACKNOWLEDGED = 3,
  PREPARING = 4,
  DELIVERING = 6,
  FULFILLED = 7,
  USER_CANCELLED = 8,
  ADMIN_CANCELLED = 9,
  FAILED = 10,
  REFUNDED = 11,
}
