export enum ORDERING_STATUS {
  PENDING = 1,
  MERCHANT_SUBMITTED = 2,
  MERCHANT_ACKNOWLEDGED = 3,
  PREPARING = 4,
  DELIVERING = 6,
  FULFILLED = 7,
  USER_CANCELLED = 8,
  ADMIN_CANCELLED = 9,
  FAILED = 10,
  REFUNDED = 11,
  READY = 5,
}

export const ORDERING_STATUS_BY_LABEL = {
  All: [
    ORDERING_STATUS.MERCHANT_SUBMITTED,
    ORDERING_STATUS.MERCHANT_ACKNOWLEDGED,
    ORDERING_STATUS.PREPARING,
    ORDERING_STATUS.DELIVERING,
    ORDERING_STATUS.FULFILLED,
    ORDERING_STATUS.REFUNDED,
    ORDERING_STATUS.READY,
    ORDERING_STATUS.USER_CANCELLED,
    ORDERING_STATUS.ADMIN_CANCELLED,
    ORDERING_STATUS.FAILED,
    ORDERING_STATUS.PENDING,
  ],
  Completed: [
    ORDERING_STATUS.MERCHANT_SUBMITTED,
    ORDERING_STATUS.MERCHANT_ACKNOWLEDGED,
    ORDERING_STATUS.PREPARING,
    ORDERING_STATUS.DELIVERING,
    ORDERING_STATUS.FULFILLED,
    ORDERING_STATUS.REFUNDED,
    ORDERING_STATUS.READY,
  ],
  Canceled: [ORDERING_STATUS.USER_CANCELLED, ORDERING_STATUS.ADMIN_CANCELLED, ORDERING_STATUS.FAILED],
  Pending: [ORDERING_STATUS.PENDING],
};

export const ORDERING_STATUS_LABEL = {
  [ORDERING_STATUS.PENDING]: 'Pending',
  [ORDERING_STATUS.USER_CANCELLED]: 'Canceled',
  [ORDERING_STATUS.ADMIN_CANCELLED]: 'Canceled',
  [ORDERING_STATUS.FAILED]: 'Canceled',
  [ORDERING_STATUS.MERCHANT_SUBMITTED]: 'Completed',
  [ORDERING_STATUS.MERCHANT_ACKNOWLEDGED]: 'Completed',
  [ORDERING_STATUS.PREPARING]: 'Completed',
  [ORDERING_STATUS.DELIVERING]: 'Completed',
  [ORDERING_STATUS.FULFILLED]: 'Completed',
  [ORDERING_STATUS.REFUNDED]: 'Completed',
  [ORDERING_STATUS.READY]: 'Completed',
};

export const ORDERING_STATUS_ICON_CLASS = {
  [ORDERING_STATUS.PENDING]: 'icon-pending',
  [ORDERING_STATUS.USER_CANCELLED]: 'icon-canceled',
  [ORDERING_STATUS.ADMIN_CANCELLED]: 'icon-canceled',
  [ORDERING_STATUS.FAILED]: 'icon-canceled',
  [ORDERING_STATUS.MERCHANT_SUBMITTED]: 'icon-completed',
  [ORDERING_STATUS.MERCHANT_ACKNOWLEDGED]: 'icon-completed',
  [ORDERING_STATUS.PREPARING]: 'icon-completed',
  [ORDERING_STATUS.DELIVERING]: 'icon-completed',
  [ORDERING_STATUS.FULFILLED]: 'icon-completed',
  [ORDERING_STATUS.REFUNDED]: 'icon-completed',
  [ORDERING_STATUS.READY]: 'icon-completed',
};

export enum ORDERS_PERIOD {
  LASTWEEK = 7,
  LAST30DAYS = 30,
  LAST90DAYS = 90,
}

export const ORDERS_PERIOD_LABEL = {
  [ORDERS_PERIOD.LASTWEEK]: 'Last Week',
  [ORDERS_PERIOD.LAST30DAYS]: 'Last 30 Day',
  [ORDERS_PERIOD.LAST90DAYS]: 'Last 90 Days',
};
