export enum ORDERING_STATUS {
  PENDING = 1,
  MERCHANT_SUBMITTED = 2,
  MERCHANT_ACKNOWLEDGED = 3,
  PREPARING = 4,
  DELIVERING = 6,
  FULFILLED = 7,
  USER_CANCELLED = 8,
  ADMIN_CANCELLED = 9,
  FAILED = 10,
  REFUNDED = 11,
  READY = 5,
}

export enum ORDERING_STATUS_LABEL_LBL {
  ALL = 'All',
  PENDING = 'Pending',
  CANCELED = 'Canceled',
  COMPLETED = 'Completed'
}

export const ORDERING_STATUS_BY_LABEL = {
  [ORDERING_STATUS_LABEL_LBL.ALL]: [
    ORDERING_STATUS.MERCHANT_SUBMITTED,
    ORDERING_STATUS.MERCHANT_ACKNOWLEDGED,
    ORDERING_STATUS.PREPARING,
    ORDERING_STATUS.DELIVERING,
    ORDERING_STATUS.FULFILLED,
    ORDERING_STATUS.REFUNDED,
    ORDERING_STATUS.READY,
    ORDERING_STATUS.USER_CANCELLED,
    ORDERING_STATUS.ADMIN_CANCELLED,
    ORDERING_STATUS.FAILED,
    ORDERING_STATUS.PENDING,
  ],
  [ORDERING_STATUS_LABEL_LBL.COMPLETED]: [
    ORDERING_STATUS.MERCHANT_SUBMITTED,
    ORDERING_STATUS.MERCHANT_ACKNOWLEDGED,
    ORDERING_STATUS.PREPARING,
    ORDERING_STATUS.DELIVERING,
    ORDERING_STATUS.FULFILLED,
    ORDERING_STATUS.REFUNDED,
    ORDERING_STATUS.READY,
  ],
  [ORDERING_STATUS_LABEL_LBL.CANCELED]: [ORDERING_STATUS.USER_CANCELLED, ORDERING_STATUS.ADMIN_CANCELLED, ORDERING_STATUS.FAILED],
  [ORDERING_STATUS_LABEL_LBL.PENDING]: [ORDERING_STATUS.PENDING],
};

export const ORDERING_STATUS_LABEL = {
  [ORDERING_STATUS.PENDING]: ORDERING_STATUS_LABEL_LBL.PENDING,
  [ORDERING_STATUS.USER_CANCELLED]: ORDERING_STATUS_LABEL_LBL.CANCELED,
  [ORDERING_STATUS.ADMIN_CANCELLED]: ORDERING_STATUS_LABEL_LBL.CANCELED,
  [ORDERING_STATUS.FAILED]: ORDERING_STATUS_LABEL_LBL.CANCELED,
  [ORDERING_STATUS.MERCHANT_SUBMITTED]: ORDERING_STATUS_LABEL_LBL.COMPLETED,
  [ORDERING_STATUS.MERCHANT_ACKNOWLEDGED]: ORDERING_STATUS_LABEL_LBL.COMPLETED,
  [ORDERING_STATUS.PREPARING]: ORDERING_STATUS_LABEL_LBL.COMPLETED,
  [ORDERING_STATUS.DELIVERING]: ORDERING_STATUS_LABEL_LBL.COMPLETED,
  [ORDERING_STATUS.FULFILLED]: ORDERING_STATUS_LABEL_LBL.COMPLETED,
  [ORDERING_STATUS.REFUNDED]: ORDERING_STATUS_LABEL_LBL.COMPLETED,
  [ORDERING_STATUS.READY]: ORDERING_STATUS_LABEL_LBL.COMPLETED,
};

export const ORDERING_STATUS_ICON_CLASS = {
  [ORDERING_STATUS.PENDING]: 'icon-pending',
  [ORDERING_STATUS.USER_CANCELLED]: 'icon-canceled',
  [ORDERING_STATUS.ADMIN_CANCELLED]: 'icon-canceled',
  [ORDERING_STATUS.FAILED]: 'icon-canceled',
  [ORDERING_STATUS.MERCHANT_SUBMITTED]: 'icon-completed',
  [ORDERING_STATUS.MERCHANT_ACKNOWLEDGED]: 'icon-completed',
  [ORDERING_STATUS.PREPARING]: 'icon-completed',
  [ORDERING_STATUS.DELIVERING]: 'icon-completed',
  [ORDERING_STATUS.FULFILLED]: 'icon-completed',
  [ORDERING_STATUS.REFUNDED]: 'icon-completed',
  [ORDERING_STATUS.READY]: 'icon-completed',
};

export enum ORDERS_PERIOD {
  PAST_SIX_MONTH = 0,
}

export const ORDERS_PERIOD_LABEL = {
  [ORDERS_PERIOD.PAST_SIX_MONTH]: 'Past 6 months',
};


