import { AddressInfo } from '../../../../core/model/address/address-info';
import { OrderItem, OrderPayment, OrderNotification } from '../models';

export interface OrderInfo {
  id: string;
  merchantName?: string;
  checkNumber: number;
  posCheckNumber: string;
  posOrderId: string;
  submittedTime: Date;
  displaySubmittedTime: string;
  dueTime: Date;
  displayDueTime: string;
  userId: string;
  userPhone: string;
  transactionId: string;
  authCode: string;
  authCodeForReverse: string;
  notificationId: string;
  deliveryFee: number;
  pickupFee: number;
  tip: number;
  useFee: number;
  subTotal: number;
  tax: number;
  total: number;
  discount: number;
  discountSource: number;
  merchantId: string;
  institutionId: string;
  type: number;
  deliveryAddressId: string;
  status: number;
  statusDetail: string;
  notes: string;
  userName: string;
  pickupAddressId: string;
  mealBased: boolean;
  mealBasedNames: string[];
  deliveryAddress: AddressInfo;
  orderItems: OrderItem[];
  orderPayment: OrderPayment[];
  orderNotifications: OrderNotification[];
}
