export function generateQuestions(): any[] {
  return [
    { type: 'header', subtype: 'h1', label: 'CBORD University New Student Application', attribute: null },
    {
      type: 'paragraph',
      subtype: 'p',
      label:
        'We are so excited you have chosen to live on campus at CBORD University! Please fill out the following application and submit it to reserve a space on campus.',
      attribute: null,
    },
    {
      type: 'checkbox-group',
      required: true,
      label: 'Please rank your top 3 residence hall choices.',
      inline: true,
      subtype: 'facilities',
      name: 'checkbox-group-1571248515993',
      preferenceCount: 3,
      values: [
        { label: '1101 - 10 Plex', value: '9000385' },
        { label: 'Stanford', value: '9000419', selected: true },
        { label: 'Able', value: '9000485', selected: true },
        { label: 'Baker', value: '9000486', selected: true },
        { label: 'Charles', value: '9000487', selected: true },
        { label: 'Davis', value: '9000488', selected: true },
        { label: 'Evans', value: '9000489', selected: true },
        { label: 'Fuller', value: '9000490' },
        { label: 'Gregory', value: '9000491' },
        { label: 'Harker', value: '9000492' },
        { label: 'Boyd', value: '9000513' },
        { label: 'Dobbs', value: '9000514' },
        { label: 'Shared Baths', value: '9000531' },
        { label: 'Apts', value: '9000538' },
        { label: 'Apartments', value: '9000541' },
        { label: 'Family Housing', value: '9000547' },
        { label: 'Alumni Hall', value: '9000554' },
        { label: 'Sarah hall', value: '9000579' },
        { label: 'Covelli Tower', value: '9000003' },
        { label: 'Harmon Hall', value: '9000004' },
        { label: 'Beckett Hall 2', value: '9000005' },
        { label: 'Jordan Hall', value: '9000035' },
        { label: 'Wilson Suites', value: '9000039' },
        { label: 'Westbrook Res Hall', value: '9000058' },
        { label: 'Silvana Hall', value: '9000148' },
        { label: 'Reef Tower', value: '9000167' },
        { label: 'Gleason Apartments', value: '9000186' },
        { label: 'Sproul Hall', value: '9000211' },
        { label: 'Lancaster', value: '9000234' },
        { label: 'York', value: '9000242' },
        { label: 'Anderson Hall', value: '9000316' },
        { label: 'Grace Hall', value: '9000344' },
        { label: '1100 - 10 Plex', value: '9000367' },
        { label: '1000 2 BR', value: '9000378' },
        { label: '1221 1 BR', value: '9000383' },
      ],
      attribute: null,
    },
    { type: 'text', label: 'Preferred Name', name: 'text-1568315394169', subtype: 'text', attribute: 'Name' },
    {
      type: 'text',
      label: 'University Student ID Number',
      name: 'text-1568315396303',
      subtype: 'text',
      attribute: 'ID Number',
    },
    { type: 'date', label: 'Date of birth', name: 'date-1568315399895', attribute: 'Date of birth' },
    {
      type: 'text',
      label: 'Cell Phone Number',
      name: 'textarea-1568315408199',
      subtype: 'textarea',
      attribute: 'Phone Number',
    },
    {
      type: 'select',
      label: 'Year:',
      name: 'select-1559676230181',
      required: true,
      order: '3',
      values: [
        {
          label: 'Freshman',
          value: '1',
        },
        {
          label: 'Sophomore',
          value: '2',
        },
        {
          label: 'Junior',
          value: '3',
        },
        {
          label: 'Senior',
          value: '4',
        },
      ],
    },
    {
      type: 'radio-group',
      required: true,
      label: 'Gender',
      name: 'radio-group-1568315413042',
      values: [
        { label: 'Female', value: 'Female', selected: false },
        { label: 'Male', value: 'Male', selected: false },
        { label: 'Transgender Female', value: 'Transgender Female', selected: false },
        { label: 'Transgender Male', value: 'Transgender Male', selected: false },
        { label: 'Non-binary', value: 'Non-binary', selected: false },
      ],
      attribute: 'Gender',
    },
    { type: 'paragraph', subtype: 'blockquote', label: 'New Page', attribute: null },

    { type: 'text', label: 'Email Address', name: 'text-1568315409856', subtype: 'text', attribute: 'Email' },
    {
      type: 'checkbox-group',
      label: 'Starting Semester',
      name: 'checkbox-group-1568315414321',
      values: [
        { label: 'Fall 2020', value: 'Fall 2020', selected: false },
        { label: 'Spring 2021', value: 'Spring 2021', selected: false },
      ],
      attribute: 'Starting Semester',
    },
    { type: 'text', label: 'Graduation Year', name: 'text-1568315415312', subtype: 'text', attribute: 'Year' },

    { type: 'paragraph', subtype: 'blockquote', label: 'New Page', attribute: null },

    { type: 'textarea', label: 'Feedback', name: 'textarea-1568315409856', subtype: 'textarea', attribute: 'Feedback' },
  ];
}
