package com.cbord.get.mcredential;

public enum EventTypes {
    INSTALL_SUCCESS,
    INSTALL_FAILURE,
    STARTUP_SUCCESS,
    STARTUP_FAILURE,
    DUPLICATED_CREDENTIAL,
    INACTIVE_CREDENTIAL,
    ENDPOINT_NOT_SETUP,
    ENDPOINT_DELETE_FAILURE,
    ENDPOINT_DELETE_SUCCESS;
}
