name: Run App Workflow

on:
  push:
    workflow_dispatch:
    branches:
      - feature/GET-6645-setup-github-actions-to-run-app
  pull_request:
    branches:
      - feature/GET-6645-setup-github-actions-to-run-app
  env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis
  API_LEVEL: 30
  ANDROID_BUILD_TOOLS_VERSION: 33.0.2
  ANDROID_SDK_PACKAGES: system-images;android-30;google_apis;x86_64 platforms;android-30 build-tools;33.0.2 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: nexus

jobs:
  webriverIo-emulator:
    timeout-minutes: 20
    
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Add avdmanager and sdkmanager to system PATH
        run: |
            echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH
      