name: Run App Workflow
'on':
  push:
    branches:
      - feature/GET-6645-setup-github-actions-to-run-app
  pull_request:
    branches:
      - feature/GET-6645-setup-github-actions-to-run-app
  workflow_dispatch: null

permissions:
  contents: read
  pages: write
  id-token: write
    
env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis
  API_LEVEL: 33
  ANDROID_BUILD_TOOLS_VERSION: 33.0.2
  ANDROID_SDK_PACKAGES: system-images;android-33;google_apis;x86_64 platforms;android-33 build-tools;33.0.2 platform-tools emulator
  EMULATOR_TIMEOUT: 700
  EMULATOR_NAME: nexus
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

jobs:
  webriverIo-emulator:
    timeout-minutes: 45
    
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Ensure cmdline-tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          curl -Lo sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip sdk-tools.zip -d $ANDROID_HOME/cmdline-tools/latest
          rm sdk-tools.zip

      - name: Add tools to PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH
      
      - name: Install SDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install ${ANDROID_SDK_PACKAGES}

      - name: Build emulator
        run: |
          echo "no" | avdmanager create avd --name $EMULATOR_NAME --abi google_apis/x86_64 -k "system-images;android-${API_LEVEL};google_apis;x86_64"
        
      - name: Launch emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd $EMULATOR_NAME -no-window -no-boot-anim -gpu swiftshader_indirect &
          adb wait-for-device




          
