export enum SETTINGS_ID {
  updatePhoto = 'update-photo',
  lostCard = 'lost-card',
  unlinkCredentials = 'unlink-credentials',
  personalData = 'email-pwd',
  password = 'pwd-change',
  biometrics = 'biometrics',
  pin = 'pin-change',
  devices = 'report-lost',
  address = 'my-address',
  mcredential = 'mobile-credential',
  paymentMethods = 'payment-methods',
  deposits = 'auto-deposits',
  mealPlan = 'meal-plan-change',
  mealPurchase = 'meal-plan-purchase',
  theme = 'theme-change',
  home = 'home-edit',
  navigate = 'nav-edit',
  feedback = 'feedback-sending',
  help = 'help',
  support = 'email-support',
  terms = 'terms-privacy',
  creditCard = 'credit-card'
}
